# Generated by Django 2.2.4 on 2020-12-20 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash_quote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='title',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='quotes_posted', to='dash_quote.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='favouriting_users',
            field=models.ManyToManyField(related_name='favourite_quotes', to='dash_quote.User'),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_text',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='quoted_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
